# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98efdc2add6beff7568cc62b8160f348e32d520bbc4ff92be045759a8bcb0532e4b5b2dc82d00d95499ac3c1b2d3ad3a9be5025bb7f0d60575ca3f4d9fea5478

test:
  secret_key_base: c612f1d0d9d987aa59dfd14cf2f45c432c95be7be7dff9ba1e38fa98d073b9cba0bfde7511541b2da536b5a12a36d133901c72cfb6c851168843f153b3275533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
